language: node_js
node_js:
- 14.17.1
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  app: mysteampro
  api_key:
    secure: sivXWHw+StIvfSyLfvpGELNznZAYhi9Fl2HpItEVdEnZLFKTsaKKrGBOWmU2OskHyXkG2MKc8ixHoLb2I1hBMiTfVs/J4tUCWGG2dfkuSWdXfSwOSjKqVab+AdOsJhD1oYMT8qPDqPVADJIOWL4lHlFevxWI+0igXutIr4DyktQd23kNXRHXiafbw6xH5aaBHWX1uSut+8CYDqJGuN+/WcFdwXLj5K0CLF168kZA7NskO5LfGcXofrc2VEh4Ml5YhZBzSGCwczi+ehD3hV6sSSI5vHTf0H22fMNuKb9CIVK38BN4cgJWQng+j2niQEHp5+A3KK4TYAc85XccUbOlaQlSGo5PBLpv2q5LzFJkwVBm3irrxMNGxjnr8bPe/Mo2pOajp80ImSx/j2T3GJ6mLr4NdrZZkPUwwcbFdItt1uN8dlD9vY8mkPnHLrB4yqCin2bxMNVjqBQvIqVvQ5yUsBtgLWPiWJw7OYu1SsSupT/dNAtU3kkOIdSmR8JM929/VgCLHkxJIr4Hn78zW+fHf2U17aCV+Ui/VJyr5qBrEMPu2F/+qlCaJxnJ/rrc+o1ddJ0wKDBEkCTqi/S+JfOLdq2u9OTNrFGSufh4lLWbQ6eJ1VssOU6oHd0dNcLf8Ghdvsfr5kLK/Hgzy2TyZZMlNIgDsMneXEWRiYoR4puQKIU=
