language: node_js
node_js:
- 14.17.1
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  app: mysteampro
  api_key:
    secure: m79NM4TFP+lMq1pBWSb5PjJWWzJ2PokfnjWNxe0nhVPRHAHpbE+ltq6C6YnRpnJers/kRpjoUAEqoR37Ickm6CjQDucSnUdtWAGlZhLC9T9mR/1mQ0ZSyaVmcaSjOLqEmhXuIT2op7cmBjeLgwQSuw5RJAUEq9v/NyuOjCZAG+mV3BCCttQu+rYxYBJkpeOUl1HK3vUamn0n5lrYmvUTReWLXV3EJOP8B8UYmvdcZ6Q1K+3R1PysFM6EjfgjDoIvIhsvT0sPAgEFxC07AC/ZWn0ljbxlXO0EMExwmUKIIuP32d7yozvL7d643VEsG73LQ8ctxw5dw9Gr+rQyBaCqg4J3UidDYyGJwr4oiUcJPQhGyT6Zm94xUnF3ULLVOBPpbDEC1cHRrx4P5xRkgBdVy9ZZrboIJNiowVPvy2DMzfcoYXquOuQGdGiHtxh0qZv65kDuz+wB0kEzR2n7T0BwAbgywPwnEM6srav/NAJPft4L8hkLmZmZEQWvoYR1ZnrLq4p8nuTvt2hltFesz3LGUeWeOA65NF2Xw314YYS6HyZJ5mrSjTaelB+k/JfTqHaha7MymPmcsdRXyNcBp3QO2hh4izE+UhG00AYQLoMNbtO5SgKKrz8QNLB5O0Ty/i0e5X6TTd+MXsjrrj+TIgq/JgIwR9P4hcR9CQ5Ppxo4aVE=
