language: node_js
node_js:
- 14.17.1
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  app: mysteampro
  api_key:
    secure: oY/ER603hWtujnqpxLrRmHwIJ3KVEOj2p3ivxFZ3biTQUunC7txEf8LTbUQjwR4F9R+CJDnVK+PTCfrOQEhq8HY1LvPD9Gf0NcTtBNa+PXDn+hfekj2MKW0Ad1k/8qoL3XzpvgCRVLf2tF69G4lvmATeA+shiX2y/P/HAMKjUOLpoY3ytGMzUaUcrRiu6JvSB0DQ1F2FYRUve/XSNW5vW0qMxtfR/WDIB6aDc8adxyqPw/ezYL2fjJUKFpNe5oAyR0u+0VgwFm+hC4TuTZulRzHaluERYhr6w37Bu+ILNK1W3XxEqN9Tiw9fT6EDeDDMGsRMabb6gkKURC70PnWe4WnADWlFNbi+u5WDb5eJ9DLzqeWZuJM7uMAQqR8wj0OJFYT8X9iRMV1FTWRqfgikkaJGYTQCJU2M1Mdnwgo/fNbNg5VL/odx861hfNktmclU6L29GgF7rtoR1P8a6J1NdbZdAXadhASY8IC4yNWicWfFzqCSJlKJn2DTwQYRQN6yigSLmRgLHqmbL1BYRn23a1t6a6czwgCeJOGCN696Dhe0ZC6RI0tRhwVcdzWG1LdWvqR2PH1uBsec8I6Uwx9HCeGeqkCljc1RdkiCOSun2AKAaXcFZEbRrA3K9/dzLILtn74c56a+GOgP6+7/TsJlgjtSzQgA/IJ9+SWtPj9b1iY=
