language: node_js
node_js:
- 14.17.1
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  app: mysteampro
  api_key:
    secure: G58upgFC9LuuFyFh3sSNRkogrHZBb8jD9Ed1MnI1DgJaB+iDJFiIMcoLvlwE3L6T7dfs764xd5dnRhD1s8Hs3PIoy+B/Y7BVQ3gjtLWMVqi50ru1BIIxssrXs3O1V6pUZym4lmBUjzjSU1nGfjv7hUeBxdgtsqB1oPNnK6WYmzjNd39dbztru0YgKGCfBkL+OA/ymAOYb7IVNgEpRh59jll5ZBPMB7zc2uYwuJkhn/7dkhrArpiBE5ZESDETBs2qJ50qstqTYQP1p0lzU+TMSlSKdGh8IlCV9LmUTmNLXrbm9vsLXTv90KiC5/7qAr/t1wzG1YMZB6yUXiJ0TeJoph4bLJw+z8N9IWfLZvhIQg7L6aW8g+lB26ZOEWK5bwkfpCEo3KBKNBLct6mnFQDTw59ldGc7nG1kMpZJOhIDchPPDdneg7Xx2yG13lKKDu1lnoLN+1IwVl//CpfMjs6wIoEv+gl2C1/siF+lCgnTophg1RQvGz9lpBukOCVQZ3Qa0d390Ss/63lQFWJtATBjbeTWUhHMDMU78QZfSPsQo91XasY63MNhMqn0CKb4quNvd1drjhHdWVOkc2TmXZB6wCQwPh9CgjEki9muKBWB4++SyJgfSu8U2WuRPAJuwsrkO3QUj8IPgv9sqY56AeMaoDmSzvftAOcS0mSfIP1AX6Q=
