language: node_js
node_js:
- 14.17.1
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  app: mysteampro
  api_key:
    secure: pw/DKz205Q/tHf9SCHNOG/1os7FxFkGzjJiFaNiOvXfQfI54P7ikvd7hVjkeYMv2Gubf2WQ1d6/SELMioDqx4thMKiUHrVGH0JyMVy8L0CtTMKC7lF4yjI3EeUpHXa88rFTNqpdDwVLFIutYrfaGPpfWZBMQWkel2iptkGe9VJF+7nXMgvjLvVvp8Lckh17sUjzoUPS0tPrlJurszkX/qfDrufDeoLwR903KnEiFtNALEu1GXoMfidIyblo+YAIKimuDt6M+bguVfJm+YF5RgszJjhgOY/CDcnDLxM9hncIDgd9uCg+jWWUnymu7qJaIq1RxQ0aba0ev67H+VxNVjJ3IId3bcT9XsVnPhCvrIVAX+Hej9NACV/Q9QainhL31BYQL2yt8eiedZ2OSJf//qDqCBi1Ls5MVv+lLnd0glMmWniRO3KAoWfr51kuqdNAsxfQitLda1U1I5AW4Eozwe/akAnfNQrHUFimRHHPF3gwE4naecaGN3KrocajZPcWqCoEnJ0+bXeqztNUGsxwVzTQriJ9kCkXEYhal4RlqEo7K0Y05IqSyg/BLnTtUbRMBMwykNU4+q9yBGyWuPIzP4L62G/lPtffsT6AYhM22ZTO0/gOS5QkF0HzIO97BLcFGvi+kGMy6ngZik7YtEY5wJJCGBdU6TpxU79V3tC0txGM=
